name: Deploy to S3 Static Site

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout the code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials (stored in repository secrets)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your AWS region

    # Step 3: Sync the files to the S3 bucket
    - name: Sync files to S3
      run: |
        aws s3 sync . s3://karthigces --delete
      # Ensure to change the path-to-your-build-output-folder and S3 bucket name
